- README.md
- cdr_plugin_folder_to_folder/Dockerfile
- cdr_plugin_folder_to_folder/api/Server.py
- cdr_plugin_folder_to_folder/common_settings/Config.py
- cdr_plugin_folder_to_folder/pre_processing/Pre_Processor.py
- docker-compose.yaml
- jupyter/Dockerfile
Integration of modules in docker-compose file
Modules include: 
cdr-f2f
jupyter notebook
elastic search
Kibana
Minio
Updated readme
> Integrated processing and other modules in docker-compose

- cdr_plugin_folder_to_folder/pre_processing/Pre_Processor.py
- cdr_plugin_folder_to_folder/pre_processing/Server.py
- cdr_plugin_folder_to_folder/pre_processing/main.py
> refactored fast api calls

- bin/dev-docker-compose.sh
- bin/dev-install-or-update-dependencies.sh
- bin/dev-start-api-server-directly.sh
- cdr_plugin_folder_to_folder/api/Server.py
- tests/unit/api/test_Server.py
- tests/unit/utils/testing/test_Test_Data.py
> added fix for "FastAPI reloading is not working"

- cdr_plugin_folder_to_folder/api/Client.py
- jupyter/notebooks/cdr_plugin_folder_to_folder_run.ipynb
script to run pre-process and process in jupyter notebook
> Jupyter notebook run script

- cdr_plugin_folder_to_folder/api/Server.py
- cdr_plugin_folder_to_folder/api/routes/Configure.py
- cdr_plugin_folder_to_folder/api/routes/Processing.py
- tests/unit/api/routes/test_Configure_Env.py
> bug found in configure env

- cdr_plugin_folder_to_folder/api/Client.py
- cdr_plugin_folder_to_folder/configure/Configure_Env.py
- jupyter/notebooks/Folder to Folder execution.ipynb
- jupyter/notebooks/jupyter_apis/API_Client.py
- tests/unit/api/routes/test_Configure_Env.py
- tests/unit/api/test_Client.py
- tests/unit/configure/test_Configure_Env_core.py
Added two more endpoints to jupyer notebook for configarations
Fixed unit tests
> Jupyter script2

- cdr_plugin_folder_to_folder/api/Client.py
- cdr_plugin_folder_to_folder/api/Server.py
- cdr_plugin_folder_to_folder/api/routes/Configure.py
- jupyter/notebooks/Folder to Folder execution.ipynb
- jupyter/notebooks/jupyter_apis/API_Client.py
- tests/unit/api/routes/test_Configure_Env.py
> Refactor v1

- .dockerignore
- infra/packer/setup/setup.sh
remove setup.sh as IP address are configured using API
> ignore .minio directory for docker context

- jupyter/notebooks/dev_jupyter_notebooks/File Report Analysis.ipynb
- jupyter/notebooks/jupyter_apis/Report_API.py
Create new python class Report
> Refactor Code

- cdr_plugin_folder_to_folder/configure/Configure_Env.py
- tests/unit/api/routes/test_Configure_Env.py
- tests/unit/configure/test_Configure_Env_core.py
Added healthcheck to gw_sdk_endpoint and validate_endpoint_json
> validate endpoints

- cdr_plugin_folder_to_folder/pre_processing/Hash_Json.py
- cdr_plugin_folder_to_folder/pre_processing/Status.py
- cdr_plugin_folder_to_folder/processing/Events_Log.py
- cdr_plugin_folder_to_folder/processing/Loops.py
hash.json and  status.json  format changes
> hash.json and status.json reformat

- cdr_plugin_folder_to_folder/common_settings/Config.py
- cdr_plugin_folder_to_folder/pre_processing/Pre_Processor.py
- cdr_plugin_folder_to_folder/processing/Analysis_Json.py
- cdr_plugin_folder_to_folder/processing/File_Processing.py
- tests/unit/pre_processing/test_Pre_Processor.py
- tests/unit/processing/test_Analysis_Json.py
- tests/unit/processing/test_File_Processing.py
Added analysis json which will have below sample structure
"087a783915875b069c89d517491dd42b9e1b3619464a750e72a7ab44c06fa645": {
"file_name": "image3.jpg",
"file_type": "jpeg",
"file_size": "97610",
"remediated_item_count": 0,
"remediate_items_list": [],
"sanitised_item_count": 0,
"sanitised_items_list": [],
"issue_item_count": 0,
"issue_item_list": []
}
> Analysis json

- jupyter/notebooks/Live Status.ipynb
- jupyter/notebooks/jupyter_apis/Show_progress.py
Total Time taken feature added
Modifed according to status api updates
> added time taken feature

- cdr_plugin_folder_to_folder/processing/Analysis_Elastic.py
- cdr_plugin_folder_to_folder/processing/Analysis_Json.py
- tests/unit/processing/test_Analysis_Elastic.py
- tests/unit/processing/test_files/analysis.json
Added analysis_json index to Elastic
> analysis elastic is updated

- cdr_plugin_folder_to_folder/configure/Configure_Env.py
- cdr_plugin_folder_to_folder/pre_processing/Status.py
Fixed error when hd2/data ,hd2/status , hd3 doesnot exists
> fixed hd2 path bug

- infra/terraform/esxi/README.md
> Ova esxi documentation

- cdr_plugin_folder_to_folder/metadata/Metadata.py
- cdr_plugin_folder_to_folder/metadata/Metadata_Service.py
- cdr_plugin_folder_to_folder/pre_processing/Pre_Processor.py
- cdr_plugin_folder_to_folder/processing/Loops.py
- tests/unit/metadata/test_Metadata_Service.py
- tests/unit/storage/test_Storage.py
"hd1_to_hd2_copy_time": 0.120714,
"hd2_to_hd3_copy_time": 23.771393
"original_hash_calculation_time": 0.094041, added
> Metadata additions

- docker-compose.yaml
- website/data/urls.yaml
- website/site/layouts/shortcodes/iframe/jupyter.html
Fixes https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/21
> Bugfix/cdr21 - jupyter notebooks not accessible from inside the cdr application

- cdr_plugin_folder_to_folder/metadata/Metadata.py
- cdr_plugin_folder_to_folder/processing/File_Processing.py
- tests/integration/processing/test_File_Processing.py
> Expand test_File_Processing

- cdr_plugin_folder_to_folder/pre_processing/Status.py
- tests/unit/pre_processing/test_Status.py
Requested update for https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/39
> Update text for NO_CLEANING_NEEDED

- jupyter/notebooks/Set_Cloud_SDK_IPs.ipynb
ISSUES:
- https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/502
> Revert the changes for v0.10.3

- website/site/assets/js/services/Services.jsx
- website/site/assets/js/services/Utils.jsx
- website/site/assets/js/style.css
- website/site/assets/js/workflows/Configuration.jsx
- website/site/assets/js/workflows/Processing.jsx
- website/site/assets/js/workflows/Workflow.jsx
- website/site/package.json
1. https://github.com/filetrust/cdr-plugin-folder-to-folder-bugs/issues/56
2. https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/437
3. https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/258
Note: manually tested on Mac machine.
> Fixed Bugs

- cdr_plugin_folder_to_folder/api/routes/Configure.py
- cdr_plugin_folder_to_folder/common_settings/Config.py
- tests/unit/api/test_Server.py
- tests/unit/common_settings/test_Config.py
Changes for -
#532 API to populate test_date directories in the UI
[API endpoint added - configuration/test_data_folders/]
> New rest api added to return sub-directories in the test-data (root) folder

- cdr_plugin_folder_to_folder/metadata/Metadata.py
- tests/unit/metadata/test_Metadata.py
Reverts filetrust/cdr-plugin-folder-to-folder#558
> Revert "Develop copy"

- .github/workflows/smoke-test.yaml
- .gitmodules
integrated bdd smoke test to cdr f2f
> Bdd test integration

- cdr_plugin_folder_to_folder/configure/Configure_Env.py
Reverts filetrust/cdr-plugin-folder-to-folder#610
> Revert "Removed verify=False in line 162"

- tests/integration/elastic/test_Dashboard_Manager.py
> Release 15 sonar cloud issue 620
